const sounds = {
  "0": "Sound0",
  "1": "Sound1",
  "2": "Sound2",
  "3": "Sound3",
  "party 1 loop short": "SoundParty1LoopS",
  "party 1 loop long": "SoundParty1LoopL",
  "party 2 loop short": "SoundParty2LoopS",
  "party 2 loop long": "SoundParty2LoopL",
  "party 3 loop short": "SoundParty3LoopS",
  "party 3 loop long": "SoundParty3LoopL",
  "party 4 loop short": "SoundParty4LoopS",
  "party 4 loop long": "SoundParty4LoopL",
  "party 5 loop short": "SoundParty5LoopS",
  "party 5 loop long": "SoundParty5LoopL",
  "party 6 loop short": "SoundParty6LoopS",
  "party 6 loop long": "SoundParty6LoopL",
  "party 7 loop short": "SoundParty7LoopS",
  "party 7 loop long": "SoundParty7LoopL",
  "party 8 loop short": "SoundParty8LoopS",
  "party 8 loop long": "SoundParty8LoopL",
  "party 9 loop short": "SoundParty9LoopS",
  "party 9 loop long": "SoundParty9LoopL",
  "party 10 loop short": "SoundParty10LoopS",
  "party 10 loop long": "SoundParty10LoopL",
  "party 11 loop short": "SoundParty11LoopS",
  "party 11 loop long": "SoundParty11LoopL",
  "party 12 loop short": "SoundParty12LoopS",
  "party 12 loop long": "SoundParty12LoopL",
  "party 13 loop short": "SoundParty13LoopS",
  "party 13 loop long": "SoundParty13LoopL",
  "strip club loop 1 short": "SoundStripClubLoop1S",
  "strip club loop 1 long": "SoundStripClubLoop1L",
  "strip club loop 2 short": "SoundStripClubLoop2S",
  "strip club loop 2 long": "SoundStripClubLoop2L",
  "work shop loop short": "SoundWorkShopLoopS",
  "work shop loop long": "SoundWorkShopLoopL",
  "sawmill loop short": "SoundSawmillLoopS",
  "sawmill loop long": "SoundSawmillLoopL",
  "38": "Sound38",
  "39": "Sound39",
  "launderette loop short": "SoundLaunderetteLoopS",
  "launderette loop long": "SoundLaunderetteLoopL",
  "chinatown restaurant short": "SoundChinatownRestaurantS",
  "chinatown restaurant long": "SoundChinatownRestaurantL",
  "cipriani resaurant short": "SoundCiprianiResaurantS",
  "cipriani resaurant long": "SoundCiprianiResaurantL",
  "46 short": "Sound46S",
  "47 long": "Sound47L",
  "marco bistro short": "SoundMarcoBistroS",
  "marco bistro long": "SoundMarcoBistroL",
  "airport loop short": "SoundAirportLoopS",
  "airport loop long": "SoundAirportLoopL",
  "shop loop short": "SoundShopLoopS",
  "shop loop long": "SoundShopLoopL",
  "cinema loop short": "SoundCinemaLoopS",
  "cinema loop long": "SoundCinemaLoopL",
  "docks loop short": "SoundDocksLoopS",
  "docks loop long": "SoundDocksLoopL",
  "home loop short": "SoundHomeLoopS",
  "home loop long": "SoundHomeLoopL",
  "frankie piano": "SoundFrankiePiano",
  "party 1 loop": "SoundParty1Loop",
  "porn cinema 1 short": "SoundPornCinema1S",
  "porn cinema 1 long": "SoundPornCinema1L",
  "porn cinema 2 short": "SoundPornCinema2S",
  "porn cinema 2 long": "SoundPornCinema2L",
  "porn cinema 3 short": "SoundPornCinema3S",
  "porn cinema 3 long": "SoundPornCinema3L",
  "bank alarm loop short": "SoundBankAlarmLoopS",
  "bank alarm loop long": "SoundBankAlarmLoopL",
  "police ball loop short": "SoundPoliceBallLoopS",
  "police ball loop long": "SoundPoliceBallLoopL",
  "rave loop industrial short": "SoundRaveLoopIndustrialS",
  "rave loop industrial long": "SoundRaveLoopIndustrialL",
  "74": "Sound74",
  "75": "Sound75",
  "police cell beating loop short": "SoundPoliceCellBeatingLoopS",
  "police cell beating loop long": "SoundPoliceCellBeatingLoopL",
  "injured ped male ouch short": "SoundInjuredPedMaleOuchS",
  "injured ped male ouch long": "SoundInjuredPedMaleOuchL",
  "injured ped female ouch short": "SoundInjuredPedFemaleOuchS",
  "injured ped female ouch long": "SoundInjuredPedFemaleOuchL",
  "evidence pickup": "SoundEvidencePickup",
  "unload gold": "SoundUnloadGold",
  "rave 1 loop short": "SoundRave1LoopS",
  "rave 1 loop long": "SoundRave1LoopL",
  "rave 2 loop short": "SoundRave2LoopS",
  "rave 2 loop long": "SoundRave2LoopL",
  "rave 3 loop short": "SoundRave3LoopS",
  "rave 3 loop long": "SoundRave3LoopL",
  "misty sex short": "SoundMistySexS",
  "misty sex long": "SoundMistySexL",
  "gate start clunk": "SoundGateStartClunk",
  "gate stop clunk": "SoundGateStopClunk",
  "part mission complete": "SoundPartMissionComplete",
  "chunky run shout": "SoundChunkyRunShout",
  "security guard away shout": "SoundSecurityGuardAwayShout",
  "race start 3": "SoundRaceStart3",
  "race start 2": "SoundRaceStart2",
  "race start 1": "SoundRaceStart1",
  "race start go": "SoundRaceStartGo",
  "swat ped shout": "SoundSwatPedShout",
  "pretend fire loop": "SoundPretendFireLoop",
  "ammunation chat 1": "SoundAmmunationChat1",
  "ammunation chat 2": "SoundAmmunationChat2",
  "ammunation chat 3": "SoundAmmunationChat3",
  "bullet hit ground 1": "SoundBulletHitGround1",
  "bullet hit ground 2": "SoundBulletHitGround2",
  "bullet hit ground 3": "SoundBulletHitGround3",
  "bullet hit water": "SoundBulletHitWater",
  "train announcement 1": "SoundTrainAnnouncement1",
  "train announcement 2": "SoundTrainAnnouncement2",
  "payphone ringing": "SoundPayphoneRinging",
  "113": "Sound113",
  "glass break long": "SoundGlassBreakL",
  "glass break short": "SoundGlassBreakS",
  "glass crack": "SoundGlassCrack",
  "glass light break": "SoundGlassLightBreak",
  "box destroyed 1": "SoundBoxDestroyed1",
  "box destroyed 2": "SoundBoxDestroyed2",
  "metal collision": "SoundMetalCollision",
  "tire collision": "SoundTireCollision",
  "gunshell drop": "SoundGunshellDrop",
  "gunshell drop soft": "SoundGunshellDropSoft",
  "total": "SoundTotal",
  "invalid": "SoundInvalid",
};

export default sounds;
