/// <reference path="blockly/core/utils/toolbox.d.ts" />
// FIXME: Types are at the path above, but not recognized by Deno
import type { ToolboxDefinition } from "blockly";

const toolbox: ToolboxDefinition = {
  kind: "categoryToolbox",
  contents: [
    {
      kind: "category",
      name: "Variables",
      colour: "330",
      contents: [
        { kind: "block", type: "var_set_bool_literal" },
        { kind: "block", type: "var_set_bool_cond" },
        { kind: "block", type: "var_set_number" },
        { kind: "block", type: "var_set_string" },
        { kind: "block", type: "var_check_bool" },
        { kind: "block", type: "var_check_number" },
      ],
    },
    {
      kind: "category",
      name: "Control Flow",
      colour: "210",
      contents: [
        { kind: "block", type: "wait", fields: { MS: 0 } },
        { kind: "label", text: "Loops" },
        { kind: "block", type: "while_true" },
        { kind: "block", type: "while" },
        { kind: "block", type: "continue" },
        { kind: "block", type: "break" },
        { kind: "label", text: "Conditions" },
        { kind: "block", type: "if" },
        { kind: "block", type: "if_or" },
        { kind: "block", type: "if_and" },
        { kind: "block", type: "if_else" },
        { kind: "label", text: "Functions" },
        { kind: "block", type: "gosub" },
        // TODO { kind: "block", type: "function" },
        // TODO { kind: "block", type: "return" },
        // TODO { kind: "block", type: "cleo_return" },
      ],
    },
    {
      kind: "category",
      name: "Mission",
      colour: "270",
      contents: [
        { kind: "block", type: "mission_given" },
        { kind: "block", type: "mission_pass" },
        { kind: "block", type: "mission_fail" },
        { kind: "block", type: "mission_finish" },
      ],
    },
    {
      kind: "category",
      name: "Text",
      colour: "160",
      contents: [
        { kind: "label", text: "Subtitles" },
        { kind: "block", type: "text_print_string" },
        { kind: "block", type: "text_print_string_and_wait" },
        { kind: "block", type: "text_clear" },
        { kind: "label", text: "Titles" },
        { kind: "block", type: "text_print_title" },
        { kind: "block", type: "text_print_title_and_wait" },
        { kind: "block", type: "text_print_big_string" },
        { kind: "block", type: "text_print_big_string_and_wait" },
        { kind: "label", text: "Help" },
        { kind: "block", type: "text_print_help" },
        { kind: "block", type: "text_clear_help" },
      ],
    },
    {
      kind: "category",
      name: "Player",
      colour: "0",
      contents: [
        { kind: "label", text: "Condition" },
        { kind: "block", type: "player_is_playing" },
        { kind: "block", type: "player_is_health_greater" },
        { kind: "block", type: "player_is_dead" },
        { kind: "block", type: "player_is_wanted_level_greater" },
        { kind: "block", type: "player_has_been_arrested" },
        { kind: "label", text: "Weapons" },
        { kind: "block", type: "player_has_weapon" },
        { kind: "label", text: "Location" },
        { kind: "block", type: "player_locate_2d" },
        { kind: "block", type: "player_locate_3d" },
        { kind: "block", type: "player_in_any_car" },
        { kind: "block", type: "player_sitting_in_car" },
        { kind: "label", text: "Miscellaneous" },
        { kind: "block", type: "player_can_start_mission" },
        { kind: "block", type: "player_lifting_phone" },
      ],
    },
    {
      kind: "category",
      name: "World",
      colour: "30",
      contents: [
        { kind: "label", text: "Pickups" },
        { kind: "block", type: "pickup_create" },
        { kind: "block", type: "pickup_collected" },
        { kind: "block", type: "pickup_remove" },
        { kind: "label", text: "Blips" },
        { kind: "block", type: "blip_for_pickup" },
        { kind: "block", type: "blip_for_coord" },
        { kind: "block", type: "blip_remove" },
      ],
    },
    {
      kind: "category",
      name: "Camera",
      colour: "75",
      contents: [
        { kind: "block", type: "camera_fade" },
        { kind: "block", type: "camera_restore" },
      ],
    },
    {
      kind: "category",
      name: "Audio",
      colour: "45",
      contents: [
        { kind: "label", text: "Audio" },
        { kind: "block", type: "audio_mission_passed" },
        { kind: "label", text: "Sound Effects" },
        { kind: "block", type: "sound_one_off" },
        { kind: "block", type: "sound_loop" },
        { kind: "block", type: "sound_remove" },
      ],
    },
  ],
};

export default toolbox;
