const toolbox = {
  kind: "categoryToolbox",
  contents: [
    {
      kind: "category",
      name: "Mission",
      colour: "270",
      contents: [
        { kind: "block", type: "mission_given" },
        { kind: "block", type: "mission_pass" },
        { kind: "block", type: "mission_fail" },
        { kind: "block", type: "mission_finish" },
      ],
    },
    {
      kind: "category",
      name: "Control Flow",
      colour: "210",
      contents: [
        { kind: "block", type: "cleo_wait", fields: { MS: 0 } },
        { kind: "block", type: "cleo_while_true" },
        { kind: "block", type: "cleo_while" },
        { kind: "block", type: "cleo_continue" },
        { kind: "block", type: "cleo_break" },
        { kind: "block", type: "cleo_if" },
        { kind: "block", type: "cleo_if_or" },
        { kind: "block", type: "cleo_if_and" },
        { kind: "block", type: "cleo_if_else" },
        { kind: "block", type: "cleo_gosub" },
      ],
    },
    {
      kind: "category",
      name: "Text",
      colour: "160",
      contents: [
        { kind: "block", type: "text_print_string" },
        { kind: "block", type: "text_print_string_and_wait" },
        { kind: "block", type: "text_clear" },
        { kind: "block", type: "text_print_title" },
        { kind: "block", type: "text_print_big_string" },
        { kind: "block", type: "text_clear_small" },
        { kind: "block", type: "text_print_help" },
        { kind: "block", type: "text_clear_help" },
      ],
    },
    {
      kind: "category",
      name: "Player",
      colour: "0",
      contents: [
        { kind: "block", type: "player_can_start_mission" },
        { kind: "block", type: "player_is_playing" },
        { kind: "block", type: "player_is_health_greater" },
        { kind: "block", type: "player_is_dead" },
        { kind: "block", type: "player_is_wanted_level_greater" },
        { kind: "block", type: "player_has_been_arrested" },
        { kind: "block", type: "player_has_weapon" },
        { kind: "block", type: "player_locate_2d" },
        { kind: "block", type: "player_locate_3d" },
        { kind: "block", type: "player_in_any_car" },
        { kind: "block", type: "player_sitting_in_car" },
        { kind: "block", type: "player_lifting_phone" },
      ],
    },
    {
      kind: "category",
      name: "World",
      colour: "30",
      contents: [
        { kind: "block", type: "pickup_create" },
        { kind: "block", type: "pickup_collected" },
        { kind: "block", type: "pickup_remove" },
        { kind: "block", type: "blip_for_pickup" },
        { kind: "block", type: "blip_for_coord" },
        { kind: "block", type: "blip_remove" },
      ],
    },
    {
      kind: "category",
      name: "Camera",
      colour: "75",
      contents: [
        { kind: "block", type: "camera_fade" },
        { kind: "block", type: "camera_restore" },
      ],
    },
    {
      kind: "category",
      name: "Audio",
      colour: "45",
      contents: [
        { kind: "block", type: "audio_mission_passed" },
        { kind: "block", type: "sound_one_off" },
        { kind: "block", type: "sound_loop" },
        { kind: "block", type: "sound_remove" },
      ],
    },
    {
      kind: "category",
      name: "Variables",
      colour: "330",
      contents: [
        { kind: "block", type: "var_set_bool_literal" },
        { kind: "block", type: "var_set_bool" },
        { kind: "block", type: "var_set_number" },
        { kind: "block", type: "var_set_string" },
        { kind: "block", type: "var_check_bool" },
        { kind: "block", type: "var_check_number" },
      ],
    },
  ],
};

export default toolbox;
